package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hecto
 */
public class Espectador extends javax.swing.JFrame {

    /**
     * Creates new form Espectador
     */
    public Espectador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulo_espectador = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        karting_btn = new javax.swing.JButton();
        moto_btn = new javax.swing.JButton();
        auto_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        camion_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pregunta_categoria = new javax.swing.JLabel();
        volverMENU_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_espectador.setBackground(new java.awt.Color(255, 255, 255));
        titulo_espectador.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        titulo_espectador.setForeground(new java.awt.Color(102, 0, 204));
        titulo_espectador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_espectador.setText("Espectador");
        jPanel2.add(titulo_espectador, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 13, 507, 45));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        karting_btn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        karting_btn.setText("Karting");
        karting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karting_btnActionPerformed(evt);
            }
        });

        moto_btn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        moto_btn.setText("Moto");
        moto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moto_btnActionPerformed(evt);
            }
        });

        auto_btn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        auto_btn.setText("Auto");
        auto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auto_btnActionPerformed(evt);
            }
        });

        camion_btn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        camion_btn.setText("Camión");
        camion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camion_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(karting_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moto_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(auto_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(camion_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(karting_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moto_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(auto_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camion_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 138, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hecto\\Downloads\\file-Photoroom.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 169, -1, -1));

        pregunta_categoria.setBackground(new java.awt.Color(255, 255, 255));
        pregunta_categoria.setFont(new java.awt.Font("Ebrima", 0, 20)); // NOI18N
        pregunta_categoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pregunta_categoria.setText("¿Qué categoría desea ver?");
        jPanel2.add(pregunta_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, 585, -1));

        volverMENU_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        volverMENU_btn.setText("Volve al Menú");
        volverMENU_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        volverMENU_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMENU_btnActionPerformed(evt);
            }
        });
        jPanel2.add(volverMENU_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 376, -1, -1));

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 700, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hecto\\Downloads\\fondo\\FONDOCOMP.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camion_btnActionPerformed
        
        registro_espectador pantalla = new registro_espectador();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_camion_btnActionPerformed

    private void auto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auto_btnActionPerformed
        
        registro_espectador pantalla = new registro_espectador();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_auto_btnActionPerformed

    private void moto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moto_btnActionPerformed
        
        registro_espectador pantalla = new registro_espectador();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_moto_btnActionPerformed

    private void karting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karting_btnActionPerformed
        registro_espectador pantalla = new registro_espectador();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_karting_btnActionPerformed

    private void volverMENU_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMENU_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverMENU_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auto_btn;
    private javax.swing.JButton camion_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton karting_btn;
    private javax.swing.JButton moto_btn;
    private javax.swing.JLabel pregunta_categoria;
    private javax.swing.JLabel titulo_espectador;
    private javax.swing.JButton volverMENU_btn;
    // End of variables declaration//GEN-END:variables
}
