/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author hecto
 */
public class opciones_espectador extends javax.swing.JFrame {

    private String usuario;

    /**
     * Creates new form opciones_espectador
     */
    public opciones_espectador() {
    }

    opciones_espectador(String usuario) {
    this.usuario = usuario;
    initComponents();
    nombre_usuario.setText("¡Bienvenido a la carrera " + usuario + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_usuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        volver_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rankinggral_btn = new javax.swing.JButton();
        volverMENU_btn = new javax.swing.JButton();
        etapas_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre_usuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nombre_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_usuario.setText("Usuario");
        nombre_usuario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                nombre_usuarioComponentAdded(evt);
            }
        });
        getContentPane().add(nombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 610, 40));

        jPanel1.setBackground(new java.awt.Color(195, 183, 197));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        volver_btn.setText("Volver");
        volver_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        volver_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_btnActionPerformed(evt);
            }
        });
        jPanel1.add(volver_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPanel2.setBackground(new java.awt.Color(195, 183, 197));

        rankinggral_btn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rankinggral_btn.setText("Ranking General");
        rankinggral_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rankinggral_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankinggral_btnActionPerformed(evt);
            }
        });

        volverMENU_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        volverMENU_btn.setText("Volve al Menú");
        volverMENU_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        volverMENU_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMENU_btnActionPerformed(evt);
            }
        });

        etapas_btn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        etapas_btn.setText("Etapas");
        etapas_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etapas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etapas_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rankinggral_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etapas_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(volverMENU_btn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rankinggral_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(etapas_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverMENU_btn)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, 590, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hecto\\Downloads\\fondo\\FONDOCOMP.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etapas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etapas_btnActionPerformed
        ranking_etapas pantalla = new ranking_etapas();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_etapas_btnActionPerformed

    private void rankinggral_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankinggral_btnActionPerformed
        ranking_gral pantalla = new ranking_gral();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_rankinggral_btnActionPerformed

    private void volverMENU_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMENU_btnActionPerformed
       
    }//GEN-LAST:event_volverMENU_btnActionPerformed

    private void volver_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_btnActionPerformed
        registro_espectador pantalla = new registro_espectador();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_volver_btnActionPerformed

    private void nombre_usuarioComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_nombre_usuarioComponentAdded
        
    }//GEN-LAST:event_nombre_usuarioComponentAdded

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton etapas_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombre_usuario;
    private javax.swing.JButton rankinggral_btn;
    private javax.swing.JButton volverMENU_btn;
    private javax.swing.JButton volver_btn;
    // End of variables declaration//GEN-END:variables
}
