/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author hecto
 */
public class registro_espectador extends javax.swing.JFrame {

    /**
     * Creates new form registro_espectador
     */
    public registro_espectador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingreso_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ingreso_usuario = new javax.swing.JTextField();
        limpiar_btn = new javax.swing.JButton();
        ingresar_btn = new javax.swing.JButton();
        volverMENU_btn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        volver_btn = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(253, 253, 253));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(195, 183, 197));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        ingreso_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_IDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        ingreso_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_usuarioActionPerformed(evt);
            }
        });

        limpiar_btn.setText("LIMPIAR DATOS");
        limpiar_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        limpiar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar_btnActionPerformed(evt);
            }
        });

        ingresar_btn.setText("INGRESAR");
        ingresar_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ingresar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingreso_ID)
                            .addComponent(ingreso_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(limpiar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ingresar_btn)
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreso_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreso_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiar_btn)
                    .addComponent(ingresar_btn))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, -1, -1));

        volverMENU_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        volverMENU_btn.setText("Volve al Menú");
        volverMENU_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        volverMENU_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMENU_btnActionPerformed(evt);
            }
        });
        getContentPane().add(volverMENU_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 301, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registro");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 12, 232, -1));

        volver_btn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        volver_btn.setText("Volver");
        volver_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        volver_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_btnActionPerformed(evt);
            }
        });
        getContentPane().add(volver_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 301, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon("C:\\Users\\hecto\\Downloads\\fondo\\FONDOCOMP.png")); // NOI18N
        FONDO.setText("jLabel3");
        FONDO.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                FONDOHierarchyChanged(evt);
            }
        });
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingreso_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreso_IDActionPerformed

    private void ingreso_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_usuarioActionPerformed

    }//GEN-LAST:event_ingreso_usuarioActionPerformed

    private void limpiar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar_btnActionPerformed
        ingreso_usuario.setText("");
        ingreso_ID.setText("");
    }//GEN-LAST:event_limpiar_btnActionPerformed

    private void ingresar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_btnActionPerformed
String usuario = ingreso_usuario.getText();
    String id = ingreso_ID.getText();
    int maxLength = 10;
    
    // Verificar que ambos campos no estén vacíos
    if (usuario.isEmpty() || id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    } else if (usuario.length() > maxLength) {
        ingreso_usuario.setText(usuario.substring(0, maxLength));
        JOptionPane.showMessageDialog(this, "El nombre de usuario no puede tener más de " + maxLength + " caracteres.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    } else {
        opciones_espectador pantalla = new opciones_espectador(usuario);
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }
    }//GEN-LAST:event_ingresar_btnActionPerformed

    private void volverMENU_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMENU_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverMENU_btnActionPerformed

    private void volver_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_btnActionPerformed
        Espectador pantalla = new Espectador();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_volver_btnActionPerformed

    private void FONDOHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_FONDOHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_FONDOHierarchyChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton ingresar_btn;
    private javax.swing.JTextField ingreso_ID;
    private javax.swing.JTextField ingreso_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar_btn;
    private javax.swing.JButton volverMENU_btn;
    private javax.swing.JButton volver_btn;
    // End of variables declaration//GEN-END:variables
}
